// developer/AxlEspiritu_S387016/Week 7 (Role-Based)/React/taskmanager-client/src/App.tsx
import { useEffect, useState } from "react";

type TaskItem = {
  id: number;
  title: string;
  isCompleted: boolean;
};

function App() {
  const [tasks, setTasks] = useState<TaskItem[]>([]);
  const [title, setTitle] = useState("");

  const apiUrl = "http://localhost:5227/api/tasks";

  async function loadTasks() {
    const response = await fetch(apiUrl);
    const data = await response.json();
    setTasks(data);
  }

  async function addTask() {
    if (!title.trim()) return;

    await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title,
        isCompleted: false,
      }),
    });

    setTitle("");
    loadTasks();
  }

  async function completeTask(task: TaskItem) {
    await fetch(`${apiUrl}/${task.id}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        id: task.id,
        title: task.title,
        isCompleted: true,
      }),
    });

    loadTasks();
  }

  async function deleteTask(id: number) {
    await fetch(`${apiUrl}/${id}`, {
      method: "DELETE",
    });

    loadTasks();
  }

  useEffect(() => {
    loadTasks();
  }, []);

  return (
    <div style={{ maxWidth: "700px", margin: "40px auto" }}>
      <h1>Task Manager</h1>

      <div style={{ marginBottom: "20px" }}>
        <input
          type="text"
          value={title}
          placeholder="Enter a new task"
          onChange={(e) => setTitle(e.target.value)}
        />

        <button onClick={addTask} style={{ marginLeft: "10px" }}>
          Add Task
        </button>
      </div>

      {tasks.map((task) => (
        <div key={task.id} style={{ marginBottom: "12px" }}>
          <span>
            {task.id}. {task.title} —{" "}
            {task.isCompleted ? "Completed" : "Pending"}
          </span>

          {!task.isCompleted && (
            <button
              onClick={() => completeTask(task)}
              style={{ marginLeft: "10px" }}
            >
              Complete
            </button>
          )}

          <button
            onClick={() => deleteTask(task.id)}
            style={{ marginLeft: "10px" }}
          >
            Delete
          </button>
        </div>
      ))}
    </div>
  );
}

export default App;

// developer/AxlEspiritu_S387016/Week 8 (Role-Based)/Angular/taskmanager-angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

type TaskItem = {
  id: number;
  title: string;
  isCompleted: boolean;
};

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App implements OnInit {

  tasks: TaskItem[] = [];
  title = '';

  apiUrl = 'http://localhost:5227/api/tasks';

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.loadTasks();
  }

  loadTasks(): void {
    this.http.get<TaskItem[]>(this.apiUrl)
      .subscribe(data => {
        this.tasks = data;
      });
  }

  addTask(): void {
    if (!this.title.trim()) {
      return;
    }

    const newTask = {
      title: this.title,
      isCompleted: false
    };

    this.http.post(this.apiUrl, newTask)
      .subscribe(() => {
        this.title = '';
        this.loadTasks();
      });
  }

  completeTask(task: TaskItem): void {

    const updatedTask = {
      id: task.id,
      title: task.title,
      isCompleted: true
    };

    this.http.put(
      `${this.apiUrl}/${task.id}`,
      updatedTask
    )
    .subscribe(() => {
      this.loadTasks();
    });
  }

  deleteTask(id: number): void {

    this.http.delete(`${this.apiUrl}/${id}`)
      .subscribe(() => {
        this.loadTasks();
      });
  }
}
