// developer/AxlEspiritu_S387016/Week 7 (Role-Based)/React/taskmanager-client/src/App.tsx
import { useEffect, useState } from "react";

type TaskItem = {
  id: number;
  title: string;
  isCompleted: boolean;
};

function App() {
  const [tasks, setTasks] = useState<TaskItem[]>([]);
  const [title, setTitle] = useState("");

  const apiUrl = "http://localhost:5227/api/tasks";

  async function loadTasks() {
    const response = await fetch(apiUrl);
    const data = await response.json();
    setTasks(data);
  }

  async function addTask() {
    if (!title.trim()) return;

    await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title,
        isCompleted: false,
      }),
    });

    setTitle("");
    loadTasks();
  }

  async function completeTask(task: TaskItem) {
    await fetch(`${apiUrl}/${task.id}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        id: task.id,
        title: task.title,
        isCompleted: true,
      }),
    });

    loadTasks();
  }

  async function deleteTask(id: number) {
    await fetch(`${apiUrl}/${id}`, {
      method: "DELETE",
    });

    loadTasks();
  }

  useEffect(() => {
    loadTasks();
  }, []);

  return (
    <div style={{ maxWidth: "700px", margin: "40px auto" }}>
      <h1>Task Manager</h1>

      <div style={{ marginBottom: "20px" }}>
        <input
          type="text"
          value={title}
          placeholder="Enter a new task"
          onChange={(e) => setTitle(e.target.value)}
        />

        <button onClick={addTask} style={{ marginLeft: "10px" }}>
          Add Task
        </button>
      </div>

      {tasks.map((task) => (
        <div key={task.id} style={{ marginBottom: "12px" }}>
          <span>
            {task.id}. {task.title} —{" "}
            {task.isCompleted ? "Completed" : "Pending"}
          </span>

          {!task.isCompleted && (
            <button
              onClick={() => completeTask(task)}
              style={{ marginLeft: "10px" }}
            >
              Complete
            </button>
          )}

          <button
            onClick={() => deleteTask(task.id)}
            style={{ marginLeft: "10px" }}
          >
            Delete
          </button>
        </div>
      ))}
    </div>
  );
}

export default App;

// developer/AxlEspiritu_S387016/Week 8 (Role-Based)/Vue/taskmanager-vue/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

type TaskItem = {
  id: number;
  title: string;
  isCompleted: boolean;
};

const tasks = ref<TaskItem[]>([]);
const title = ref("");

const apiUrl = "http://localhost:5227/api/tasks";

async function loadTasks() {
  const response = await fetch(apiUrl);
  tasks.value = await response.json();
}

async function addTask() {
  if (!title.value.trim()) return;

  await fetch(apiUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title: title.value,
      isCompleted: false,
    }),
  });

  title.value = "";
  await loadTasks();
}

async function completeTask(task: TaskItem) {
  await fetch(`${apiUrl}/${task.id}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      id: task.id,
      title: task.title,
      isCompleted: true,
    }),
  });

  await loadTasks();
}

async function deleteTask(id: number) {
  await fetch(`${apiUrl}/${id}`, {
    method: "DELETE",
  });

  await loadTasks();
}

onMounted(() => {
  loadTasks();
});
</script>

<template>
  <main class="container">
    <h1>Vue Task Manager</h1>

    <div class="add-task">
      <input
        v-model="title"
        type="text"
        placeholder="Enter a new task"
        @keyup.enter="addTask"
      />

      <button @click="addTask">
        Add Task
      </button>
    </div>

    <div
      v-for="task in tasks"
      :key="task.id"
      class="task"
    >
      <span>
        {{ task.id }}. {{ task.title }} —
        {{ task.isCompleted ? "Completed" : "Pending" }}
      </span>

      <button
        v-if="!task.isCompleted"
        @click="completeTask(task)"
      >
        Complete
      </button>

      <button @click="deleteTask(task.id)">
        Delete
      </button>
    </div>
  </main>
</template>

<style scoped>
.container {
  max-width: 700px;
  margin: 40px auto;
  font-family: Arial, sans-serif;
}

.add-task {
  margin-bottom: 20px;
}

input {
  padding: 8px;
  width: 300px;
}

button {
  margin-left: 10px;
  padding: 8px 12px;
  cursor: pointer;
}

.task {
  margin-bottom: 12px;
}
</style>
